# -*- coding: utf-8 -*-
"""Doubts and practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HVmKIqw_mAFQTq-eSOOQB3GoSZjHth1z
"""

#Excercise 1: Swap the number without using third varible

a=10
b=20
print("before a",a)
print("before b",b)
a,b=b,a
print("after swap a",a)
print("after swap b",b)

a = 5,6 #packing - pack them in a tuple

a

e,f = a #unpacking

e

f

a=5
b=2
a=a+b
b=a-b
a = a-b
print('After swapping:',a,b)



"""Exercise 2: Write a Program to extract each digit from an integer in the reverse order.
1234
4 3 2 1
"""

# def reverse_integer(number):
#   num = int(input("enter number"))
#   while num
#     num1= num % 10
#     print(num1)
#     num = num // 10

# orginal_number=12345
# reversed_number = reverse_integer(original_number)
# print("Original number:", original_number)
# print("Reversed number:", reversed_number)

orginal_number=457568
def reverse_integer(number):
  while number:
    l = number%10 #last digit
    number = number//10
    # print("last digit",l)
    # print("remaing digt",number)
    #print(l,end='\n') original; print
    print(l,end=' ') #original; print
reverse_integer(orginal_number)

orginal_number%10

